config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :places, only: [:index, :show, :create, :new]
  get 'categories', to: 'pages#categories'
  resources :places do
    member do
      put 'upvote'
      put 'unvote'
      put 'upvotes'
      put 'unvotes'
    end
  end
  get 'likedplaces', to: 'places#likedplaces'
  get 'showplace', to: 'places#showplace'
  get 'map', to: 'places#map'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  validates :name, :category, :description, :summary, :address, presence: true
  validates :description, length: { minimum: 200, maximum: 405 }
  validates :summary, length: { minimum: 10, maximum: 200 }
  validates :address, uniqueness: true
  validates :description, length: { minimum: 200 }
  validates :description, length: { maximum: 405 }
  validates :summary, length: { minimum: 10 }
  validates :summary, length: { maximum: 100 }
  validates :photo, presence: true

  acts_as_votable

  CATEGORIES = ['food', 'nightlife', 'activities', 'shopping', 'services']

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @location = request.location.coordinates
  end

  def categories
    @spot = params[:format]
    @categories = ['food', 'nightlife', 'activities', 'shopping', 'services']
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @category = params[:category]
    @location = params[:spot]
    placesold = Place.where(category: params[:category])
    @places = placesold.near(@location, 5)
    Cloudinary.config do |config|
      config.cloud_name = 'mk01'
      config.api_key = '243339615997478'
      config.api_secret = 'YEyzNmKecdmScbJTs5wcY3KFlO8'
      config.secure = true
      config.cdn_subdomain = true
    end
  end

  def show
    @user = current_user
    @location = params[:spot]
    @place = Place.find(params[:id])
    Cloudinary.config do |config|
      config.cloud_name = 'mk01'
      config.api_key = '243339615997478'
      config.api_secret = 'YEyzNmKecdmScbJTs5wcY3KFlO8'
      config.secure = true
      config.cdn_subdomain = true
    end
  end

  def new
    @place = Place.new
    Cloudinary.config do |config|
      config.cloud_name = 'mk01'
      config.api_key = '243339615997478'
      config.api_secret = 'YEyzNmKecdmScbJTs5wcY3KFlO8'
      config.secure = true
      config.cdn_subdomain = true
    end
  end

  def create
    @place = Place.new(places_params)
    @place.user = current_user
    if @place.save
      redirect_to "/", notice: '***Thank you for uploading your yudget!***'
    else
      render :new
    end
    Cloudinary.config do |config|
      config.cloud_name = 'mk01'
      config.api_key = '243339615997478'
      config.api_secret = 'YEyzNmKecdmScbJTs5wcY3KFlO8'
      config.secure = true
      config.cdn_subdomain = true
    end
  end

  def upvote
    @location = params[:spot]
    @place = Place.find(params[:id])
    @place.liked_by current_user
    redirect_to place_path(@place, :spot => @location)
  end

  def unvote
    @location = params[:spot]
    @place = Place.find(params[:id])
    @place.downvote_from current_user
    redirect_to place_path(@place, :spot => @location)
  end

  def upvotes
    @category = params[:category]
    @location = params[:spot]
    @place = Place.find(params[:id])
    @place.liked_by current_user
    placesold = Place.where(category: params[:category])
    @places = placesold.near(@location, 3)
    redirect_to places_path(@place, :category => @category, :spot => @location)
  end

  def unvotes
    @category = params[:category]
    @location = params[:spot]
    @place = Place.find(params[:id])
    @place.downvote_from current_user
    placesold = Place.where(category: params[:category])
    @places = placesold.near(@location, 3)
    redirect_to places_path(@place, :category => @category, :spot => @location)
  end

  def likedplaces
    @places = Place.all
    @user = current_user
  end

  def showplace
    @user = current_user
    @place = Place.find(params[:id])
    Cloudinary.config do |config|
      config.cloud_name = 'mk01'
      config.api_key = '243339615997478'
      config.api_secret = 'YEyzNmKecdmScbJTs5wcY3KFlO8'
      config.secure = true
      config.cdn_subdomain = true
    end
  end

  def map
    @places = Place.all
    @markers = @places.geocoded.map do |place|
      {
        lat: place.latitude,
        lng: place.longitude,
        info_window: render_to_string(partial: "info_window", locals: { place: place })
      }
    end
  end

  private

  def places_params
    params.require(:place).permit(:name, :category, :description, :summary, :address, :photo, :user).with_defaults(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yudget | Enjoy life on a budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">

    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/categories.html.erb
<div id="category">
<h1 id="categories-header"><center>what are you looking for?</center></h1>
<div id="categories">
<% @categories.each do |category| %>
<%= link_to places_path(:category => category, :spot => @spot) do %>
  <div class="card">
    <h1 id="categoryeach"><%= category %></h1>
  </div>
<% end %>
<% end %>

</div>
</div>

app/views/pages/home.html.erb
<div class="d flex aligh items center">
  <%# <div class="main-text-homepage"> %>
    <div class="main-container">
          <div class="homepage-searchbox">
          <div class="text-homepage">
              <h1 class= "main-header1">YUDGET</h1>
                <h1 class= "main-header" id="javascript"></h1>
                <%= form_with url: "/categories", method: :get do |form| %>
                  <%#= form.label :format, "Type in the address " %>
                  <%= form.text_field :format, placeholder:"Type address to find Yudgets" , class:"search-form" %>
                  <%= form.submit "Search" , class: "btn-homepage" %>
                <% end %>

                <p>or</p>
                <div class="your-location-button">
                <%= link_to "Select your current location", categories_path(:format => '138 Kingsland Rd, London E2 8DY')  %>
                </div>
          </div>
          </div>
          <div class="blue-block">
        </div>


      </div>

    </div>
  </div>
</div>
</div>

</div>
<div class="image-home-page">
        <%#= image_tag asset_url('homepagepic.png') %>
        <%= image_tag 'https://user-images.githubusercontent.com/72749819/131869602-20480bfe-a25f-4999-9b7e-8f77fc42a96d.png', class:'main-pic'%>
</div>

app/views/places/_info_window.html.erb
<h2><%= link_to "#{place.name}", showplace_path(:id => place.id) %></h2>
<h5><%= place.category %></h5>
<h6><%= link_to "#{place.address}", "https://maps.google.com/?q=#{place.address}", :target => "_blank" %></h6>

app/views/places/index.html.erb
<div id="places">
  <h1 id="places-header"><center>yudgets</center></h1>
  <% (@places.sort_by {|obj| obj.get_upvotes.size }).reverse.each do |place| %>
    <div class="card-product">
      <% if place.photo.attached? %>
        <%=cl_image_tag place.photo.key%>
      <% else  %>
        <img src="https://media.timeout.com/images/103070427/image.jpg" width=70% class="place-img-left" alt="...">
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to "#{place.name}  -  #{(place.distance_to(@location) * 1000).round} meters away", place_path(place, :spot => @location) %></h2>
        <p>                                                   </p>
        <h3><%= place.summary %><h3>
      </div>
      <div id="placehold" class="d-flex mb-3 flex-column align-items-center justify-content-center" align="right">
        <% if current_user.liked?(place, :spot => @location) %>
          <div>
            <%= link_to unvotes_place_path(place, :category => @category, :spot => @location),  method: :put, remote: true do%>
              <i class="fas fa-heart fa-3x"></i>
            <% end %>
          </div>
        <% else %>
          <div>
            <%= link_to upvotes_place_path(place, :category => @category, :spot => @location), method: :put, remote: true do%>
              <i class="far fa-heart fa-3x"></i>
            <% end %>
          </div>
        <% end %>
        <h3 id="johannes"><%= place.get_upvotes.size %></h3>
      </div>
    </div>
  <% end %>
</div>

app/views/places/likedplaces.html.erb
<h1 id="places-header"><center>liked yudgets</center></h1>
<% @places.each do |place| %>
<% if current_user.liked?(place) %>
  <div class="card-product">
      <% if place.photo.attached? %>
        <%=cl_image_tag place.photo.key%>
      <% else  %>
        <img src="https://media.timeout.com/images/103070427/image.jpg" width=70% class="place-img-left" alt="...">
      <% end %>
      <div class="card-product-infos">
        <h2><%= link_to "#{place.name}", showplace_path(:id => place.id) %></h2>
        <p>                                                   </p>
        <h3><%= place.summary %><h3>
    </div>
    <% end %>
    </div>
<% end %>

app/views/places/map.html.erb
<div id="map"
     style="width: 80%; height: 600px; margin-left: 150px; margin-top: 50px; border: 4px solid #4C6487; "
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="pk.eyJ1IjoiYWxiZXJ0a2Vlbm8iLCJhIjoiY2t0OXRzZncyMWZuaDJvcGVwNm13YmFoZSJ9._Uo4gAk3KV-ANVJQLc_WaQ">
</div>

app/views/places/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-12 col-sm-8 col-sm-offset-8">
      <div class="form-new-yudget">
          <h1>Add a Yudget for the community</h1>
            <%= simple_form_for (@place) do |c| %>
              <%= c.input :name, placeholder: 'What is the name of your Yudget place?' %>
              <%= c.input :category, collection:['food', 'nightlife', 'activities', 'shopping', 'services'], placeholder: 'Whats is the category for your Yudget place?' %>
              <%= c.input :description, placeholder: 'Leave a description of the place and what you enjoyed most about it (min. 200 characters)',input_html: { minlength: 200, maxlength: 405  } %>
              <%= c.input :summary, placeholder: 'Briefly state the reasons for recommending this yudget',input_html: { maxlength: 100 } %>
              <%= c.input :address, as: :string, placeholer: 'Please enter the full address of your Yudget', input_html: { id: 'place_address' } %>
              <%= c.input :photo, as: :file %>
              <%= c.submit 'Create new Yudget' , class: 'btn btn-primary' %>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/places/show.html.erb
<div id="show">
  <div class="card p-3 shadow" style=" max-width: 80%;">
      <div class="d-flex justify-content-center mt-2">
        <h1 id="youdget"> <%= @place.name %></h1>
        <div id="upvote" class="d-flex flex-column align-items-center justify-content-center">
            <% if current_user.liked?(@place, :spot => @location) %>
              <div><%= link_to unvote_place_path(@place, :spot => @location),  method: :put, remote: true do%>
              <i class="fas fa-heart fa-3x"></i></div> <% end %>
            <% else %>
              <div><%= link_to upvote_place_path(@place, :spot => @location), method: :put, remote: true do%>
              <i class="far fa-heart fa-3x"></i></div><% end %>
            <% end %>
          <div id="vote_counter"class="total_upvotes">
            <%= @place.get_upvotes.size %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-evenly align-items-center mt-2">
        <div class="row p-4">
          <div class="col-lg-6 ">
            <% if @place.photo.attached? %>
              <%= cl_image_tag @place.photo.key, height: 350, width: 500, crop: :fill%>
            <% else  %>
            <img src="https://media.timeout.com/images/103070427/image.jpg"  class="place-img-top w-100" alt="...">
            <% end %>
          </div>
          <div class="col-lg-6 justify-content-center">
            <h3> <%= @place.description %></h3>
          </div>
        </div>
      </div>
          <div class="text-center">
            <h1 class="btn btn-primary"> <%= link_to "Take me there!", "https://maps.google.com/?q=#{@place.address}", :target => "_blank",style:"color: white; text-decoration: none;" %></h1>
          <h4 class="text-muted mb-2"> <%= (@place.distance_to(@location) * 1000).round %> meters away</h4>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/places/showplace.html.erb
<div id="show">
  <div class="card p-3 shadow" style=" max-width: 80%;">
      <div class="d-flex justify-content-center mt-2">
        <h1 id="youdget"> <%= @place.name %></h1>
        <div id="upvote">
              <% if current_user.liked?(@place, :spot => @place.address) %>
                  <div><%= link_to unvote_place_path(@place, :spot => @place.address),  method: :put, remote: true do%>
                  <i class="fas fa-heart fa-3x"></i></div> <% end %>
                <% else %>
                  <div><%= link_to upvote_place_path(@place, :spot => @place.address), method: :put, remote: true do%>
                  <i class="far fa-heart fa-3x"></i></div><% end %>
              <% end %>
          <div id="vote_counter"class="total_upvotes">
            <%= @place.get_upvotes.size %>
          </div>
        </div>
      </div>
      <div class="d-flex justify-content-evenly align-items-center mt-2">
      <div class="row p-5">
          <div class="col-lg-6 ">
            <% if @place.photo.attached? %>
              <%= cl_image_tag @place.photo.key, height: 350, width: 500, crop: :fill%>
            <% else  %>
            <img src="https://media.timeout.com/images/103070427/image.jpg"  class="place-img-top w-100" alt="...">
            <% end %>
          </div>
          <div class="col-lg-6 justify-content-center">
            <h3> <%= @place.description %></h3>
          </div>
        </div>
      </div>
          <div class="text-center">
            <h1 class="btn btn-primary"> <%= link_to "#{@place.address}", "https://maps.google.com/?q=#{@place.address}", :target => "_blank",style:"color: white; text-decoration: none;" %></h1>
          </div>
      </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "https://user-images.githubusercontent.com/84774608/132191553-626a0347-01b5-463e-94e0-eaf8b228da35.png" %>
    <% end %>
  <div class="addyudget">
    <h4><u><%= link_to "ADD A YUDGET", new_place_path %></u></h4>
  </div>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
      <%= image_tag "https://user-images.githubusercontent.com/72749819/132351120-ef89474c-bb99-4a89-98d4-a37e9b908074.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "LIKED YUDGETS", likedplaces_path, class: "dropdown-item" %>
          <%= link_to "MAP", map_path, class: "dropdown-item" %>
      <% if user_signed_in? %>
          <%= link_to "LOG OUT", destroy_user_session_path, class: "dropdown-item", method: :delete %>
        </li>
      <% else %>
          <%= link_to "LOGIN", new_user_session_path, class: "dropdown-item " %>
        </li>
      <% end %>
      </div>
      </li>
    </ul>
  </div>
</div>